language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script:
  - php tests/massage-composer-for-testing.php
  - COMPOSER=tests/composer.json composer install --dev

script: phpunit --coverage-text --verbose
